language: ruby
cache: bundler
rvm: 2.4
script:
  - bundle exec rspec spec/unit
  - bundle exec rubocop
deploy:
  - provider: releases
    api_key:
      secure: xg82SFFS5Vd99DV6F+9O81Y1yQL/7VMPlSQOMWLY8ZNFkoUsimdKMqNFVuLx2quy7Ui1CtXS4SEb1bdLo+JmmV5Wlrzwjx37l+WMHz3znng3V3UiLnTKlyeKaXFr1meKaFFltdN/p2dTSPaMamw0sbFk+ZvdT1AelFT0lHIouans/WydTOCiUURZ4qrVAUbaC63dV5vWC+7Qo0F9wkRSrXdpbF82xxJF2bH1ZCLZrmAgFkVjSbGZAJReMcfAbZB6Y59J+dKiXF31ycH8upkkbp7VHyA7b0F1/RZKfEnJ3kOs5N1wPwQF32esCe5WSaziqWKgNUpXbYFcvFliTrYq52PbUiwc1BvJnWFLuIMqZe4Av0McmYcJ561b+hnCm6/cPuCrnuYajyoPArbI6ir5JUEgzRl3nSF+T/sQph7iMX1j4LnotgTFRO3Erm10oRA6Z8AEwMEIzW38WdGgEpBt7EaQZ4ANk2PNBF7UXpVM26SilJc+2YpROcVVpMPR+6WuMUSamuLGTNc5juMemnKGpeNWIkEL1x0weztuENvwJlwyDprRfzVjnHxgQAJEUrTf5alyKkbnPBa0iZoqF/vCDoaG5utvWG7ct91pJfWKbxZt7rYzNRYBGwR8dJbq/H8eXie70J5izzwqz5Nyk2nWPadnVg8onpWGg0OUWo/lffw=
    file_glob: true
    file: manifestly-client-*.gem
    on:
      tags: true
      rvm: 2.4
      repo: firespring/manifestly-ruby
